# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
# - stage: Build
#   displayName: Build docker image
#   jobs:
#   - job: Build
#     displayName: Build
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         containerRegistry: 'yhub'
#         repository: 'yhub/hello-world-asp-net-core'
#         command: 'buildAndPush'
#         Dockerfile: '**/Dockerfile'

- stage: Run
  displayName: Run docker image
  jobs:
  - job: Apply
    displayName: Apply kubectl bb.yml
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'None'
        namespace: 'spec.serviceAccountName'
        command: 'apply'
        useConfigurationFile: true
        # configuration: '$(Build.SourceDirectory)/bb.yml'
        configuration: $(System.DefaultWorkingDirectory)/bb.yml
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        useConfigMapFile: true
        configMapFile: 'bb.yml'

    # - task: Kubernetes@1
    #   inputs:
    #     connectionType: 'None'
    #     namespace: 'spec.serviceAccountName'
    #     command: 'create'
    #     useConfigurationFile: true
    #     configurationType: 'inline'
    #     inline: 'kubectl create deployment hello-world-asp-net-core hello-world-asp-net-core=yhub/hello-world-asp-net-core:$(Build.BuildId)'
    #     secretType: 'dockerRegistry'
    #     containerRegistryType: 'Container Registry'
    #     dockerRegistryEndpoint: 'yhub'