# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# - script: dotnet build --project 'yfereidouni/helloworld' --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
- script: echo $(environment) Job_01!
- script: echo $(Build.BuildNumber)
- script: echo $(Build.BuildId)
- script: echo $(Build.SourceBranchName)
- script: echo $(Build.SourceDirectory)
- script: echo $(System.DefaultWorkingDirectory)
- script: echo ls -R $(System.DefaultWorkingDirectory)
- script: echo $(Build.ArtifactStagingDirectory)

- script: dotnet build --project /home/vsts/work/1/s/HelloWorld/HelloWorld.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# - task: UseDotNet@2
#   inputs:
#     packageType: 'sdk'
#     version: 
#     vsVersion: '6.0'
# - task: DotNetCoreCLI@2
#   inputs:
#     command: publish
#     publishWebProjects: True
#     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#     zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: Publishing Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
