apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-asp-net-core
  name: hello-world-asp-net-core
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-asp-net-core
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-asp-net-core
    spec:
      containers:
      - image: yhub/hello-world-asp-net-core:0
        imagePullPolicy: IfNotPresent
        name: hello-world-asp-net-core
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-asp-net-core
  name: hello-world-asp-net-core
  namespace: default
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 5000
    targetPort: 80
    protocol: TCP
  selector:
    app: hello-world-asp-net-core
  sessionAffinity: None
  type: LoadBalancer